// GENERATED by scripts/build-portable.ts - measured from the files that were
// just written, so a size shown in the UI is never a stale guess. Do not edit.

export const artifactSizes: Record<string, { bytes: number; tokens: number }> = {
  "llms-full.txt": {
    "bytes": 287803,
    "tokens": 71951
  },
  "llms.txt": {
    "bytes": 22306,
    "tokens": 5577
  },
  "foundations.md": {
    "bytes": 17013,
    "tokens": 4253
  },
  "guidance.md": {
    "bytes": 13472,
    "tokens": 3368
  },
  "api.json": {
    "bytes": 107656,
    "tokens": 26914
  },
  "tokens.css": {
    "bytes": 23419,
    "tokens": 5855
  },
  "inspera.theme.css": {
    "bytes": 4943,
    "tokens": 1236
  },
  "tokens.w3c.json": {
    "bytes": 13987,
    "tokens": 3497
  },
  "aliases.json": {
    "bytes": 3517,
    "tokens": 879
  }
}
