// GENERATED by scripts/build-portable.ts from the component TypeScript
// interfaces. Do not edit. Regenerate with `pnpm generate`.

import type { PropDoc } from '../../scripts/extract-props'

export type { PropDoc }

export const componentApi: Record<string, PropDoc[]> = {
  "Accordion": [
    {
      "name": "items",
      "type": "AccordionItem[]",
      "required": false,
      "default": "defaultItems",
      "description": "Accordion sections."
    },
    {
      "name": "type",
      "type": "'Single' | 'Multiple'",
      "required": false,
      "default": "'Single'",
      "description": "Allow one or many open at once. Values: Single | Multiple."
    },
    {
      "name": "defaultOpenIndex",
      "type": "number",
      "required": false,
      "default": "0",
      "description": "Initially open section."
    },
    {
      "name": "iconPosition",
      "type": "'Left' | 'Right'",
      "required": false,
      "default": "'Right'",
      "description": "Chevron placement. Values: Left | Right."
    }
  ],
  "Alert": [
    {
      "name": "title",
      "type": "string",
      "required": false,
      "default": "'Heads up'"
    },
    {
      "name": "message",
      "type": "string",
      "required": false,
      "default": "'This is a contextual inline message that matches the intent severity.'"
    },
    {
      "name": "intent",
      "type": "'Info' | 'Success' | 'Warning' | 'Error'",
      "required": false,
      "default": "'Info'",
      "description": "Severity / color. Values: Info | Success | Warning | Error."
    },
    {
      "name": "layout",
      "type": "'Simple' | 'With CTA' | 'With Close' | 'With CTA + Close'",
      "required": false,
      "default": "'Simple'",
      "description": "Action affordances. Values: Simple | With CTA | With Close | With CTA + Close."
    },
    {
      "name": "background",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Tinted fill vs. left-accent only. Values: true | false."
    },
    {
      "name": "ctaLabel",
      "type": "string",
      "required": false,
      "default": "'View details'"
    },
    {
      "name": "onCta",
      "type": "() => void",
      "required": false
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": false
    }
  ],
  "Avatar": [
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Diameter 32 / 40 / 56. Values: Small | Medium | Large."
    },
    {
      "name": "content",
      "type": "'Image' | 'Initials' | 'Icon'",
      "required": false,
      "default": "'Initials'",
      "description": "What fills the avatar. Values: Image | Initials | Icon."
    },
    {
      "name": "status",
      "type": "'None' | 'Online' | 'Offline' | 'Busy'",
      "required": false,
      "default": "'None'",
      "description": "Presence indicator dot. Values: None | Online | Offline | Busy."
    },
    {
      "name": "initials",
      "type": "string",
      "required": false,
      "default": "'JC'"
    },
    {
      "name": "imageSrc",
      "type": "string",
      "required": false,
      "default": "'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=112&h=112&fit=crop&auto=format'"
    },
    {
      "name": "alt",
      "type": "string",
      "required": false,
      "default": "'User avatar'"
    },
    {
      "name": "icon",
      "type": "string",
      "required": false,
      "default": "'person'"
    }
  ],
  "AvatarGroup": [
    {
      "name": "avatars",
      "type": "AvatarGroupItem[]",
      "required": false,
      "default": "defaultAvatars",
      "description": "Avatars to display."
    },
    {
      "name": "max",
      "type": "number",
      "required": false,
      "default": "4",
      "description": "Maximum shown before overflow."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Avatar diameter. Values: Small | Medium | Large."
    }
  ],
  "Badge": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Badge'"
    },
    {
      "name": "intent",
      "type": "'Info' | 'Success' | 'Warning' | 'Error' | 'Neutral'",
      "required": false,
      "default": "'Neutral'",
      "description": "Semantic color. Values: Neutral | Info | Success | Warning | Error."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Height 20 / 24. Values: Small | Medium."
    },
    {
      "name": "withIcon",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Show a leading status icon. Values: true | false."
    },
    {
      "name": "icon",
      "type": "string",
      "required": false
    }
  ],
  "Breadcrumb": [
    {
      "name": "items",
      "type": "string[]",
      "required": false,
      "default": "defaultItems"
    },
    {
      "name": "separator",
      "type": "'Slash' | 'Chevron'",
      "required": false,
      "default": "'Chevron'",
      "description": "Divider glyph between items. Values: Slash | Chevron."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Text size 14 / 16. Values: Small | Medium."
    },
    {
      "name": "onNavigate",
      "type": "(index: number) => void",
      "required": false
    }
  ],
  "Button": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Button'"
    },
    {
      "name": "intent",
      "type": "'Success' | 'Warning' | 'Primary' | 'Secondary' | 'Outline' | 'Text' | 'Destructive'",
      "required": false,
      "default": "'Primary'",
      "description": "Visual role / semantic weight. Values: Primary | Secondary | Outline | Text | Success | Warning | Destructive."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Height 32 / 40 / 48. Values: Small | Medium | Large."
    },
    {
      "name": "state",
      "type": "'Default' | 'Hover' | 'Focused' | 'Pressed' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "content",
      "type": "'Text' | 'Icon + Text' | 'Text + Icon' | 'Text + Disclosure'",
      "required": false,
      "default": "'Text'",
      "description": "Label / icon composition. Values: Text | Icon + Text | Text + Icon | Text + Disclosure."
    },
    {
      "name": "icon",
      "type": "string",
      "required": false,
      "default": "'add'"
    },
    {
      "name": "onClick",
      "type": "() => void",
      "required": false
    }
  ],
  "Card": [
    {
      "name": "title",
      "type": "string",
      "required": false,
      "default": "'Card title'"
    },
    {
      "name": "body",
      "type": "string",
      "required": false,
      "default": "'Group related content in a contained surface using consistent padding and elevation.'"
    },
    {
      "name": "elevation",
      "type": "'Flat' | 'Raised' | 'Outlined'",
      "required": false,
      "default": "'Raised'",
      "description": "Surface treatment. Values: Flat | Raised | Outlined."
    },
    {
      "name": "padding",
      "type": "'Default' | 'Compact' | 'Spacious'",
      "required": false,
      "default": "'Default'",
      "description": "Internal padding (12 / 16 / 24). Values: Compact | Default | Spacious."
    },
    {
      "name": "interactive",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Renders as a focusable button with hover elevation. Values: true | false."
    },
    {
      "name": "children",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false
    },
    {
      "name": "onClick",
      "type": "() => void",
      "required": false
    }
  ],
  "Checkbox": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Checkbox label'"
    },
    {
      "name": "checked",
      "type": "boolean",
      "required": false,
      "description": "Checked state. Values: true | false."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Hover' | 'Focused' | 'Pressed' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "withLabel",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Render the label. Values: true | false."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Indicator size. Values: Small | Medium."
    },
    {
      "name": "onChange",
      "type": "(checked: boolean) => void",
      "required": false
    }
  ],
  "CheckboxGroup": [
    {
      "name": "label",
      "type": "string",
      "required": false
    },
    {
      "name": "options",
      "type": "CheckboxOption[]",
      "required": false,
      "default": "DEFAULT_OPTIONS",
      "description": "Checkbox options."
    },
    {
      "name": "value",
      "type": "string[]",
      "required": false,
      "description": "Selected option values."
    },
    {
      "name": "orientation",
      "type": "'Vertical' | 'Horizontal'",
      "required": false,
      "default": "'Vertical'",
      "description": "Layout direction. Values: Vertical | Horizontal."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "onChange",
      "type": "(value: string[]) => void",
      "required": false
    }
  ],
  "DatePicker": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Date'"
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Selected date (YYYY-MM-DD)."
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "default": "'Select date'",
      "description": "Trigger placeholder."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Focused' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the field label. Values: true | false."
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Open the calendar initially. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(iso: string) => void",
      "required": false
    }
  ],
  "Dialog": [
    {
      "name": "title",
      "type": "string",
      "required": false,
      "default": "'Dialog title'"
    },
    {
      "name": "body",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false,
      "default": "'This is the dialog body. Provide context or a clear description of the action the user is about to take.'"
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Panel width 400 / 480 / 560. Values: Small | Medium | Large."
    },
    {
      "name": "hasCloseButton",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the header close affordance. Values: true | false."
    },
    {
      "name": "hasActions",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the footer action buttons. Values: true | false."
    },
    {
      "name": "confirmLabel",
      "type": "string",
      "required": false,
      "default": "'Continue'"
    },
    {
      "name": "cancelLabel",
      "type": "string",
      "required": false,
      "default": "'Cancel'"
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false,
      "default": "true"
    },
    {
      "name": "embedded",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Render just the panel (no overlay) — used for documentation previews."
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": false
    },
    {
      "name": "onConfirm",
      "type": "() => void",
      "required": false
    }
  ],
  "Divider": [
    {
      "name": "orientation",
      "type": "'Vertical' | 'Horizontal'",
      "required": false,
      "default": "'Horizontal'",
      "description": "Divider direction. Values: Horizontal | Vertical."
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Optional centered label (horizontal only)."
    },
    {
      "name": "spacing",
      "type": "'Default' | 'Compact' | 'Spacious'",
      "required": false,
      "default": "'Default'",
      "description": "Surrounding margin. Values: Compact | Default | Spacious."
    }
  ],
  "Drawer": [
    {
      "name": "open",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Visibility. Values: true | false."
    },
    {
      "name": "side",
      "type": "'Left' | 'Right' | 'Bottom'",
      "required": false,
      "default": "'Right'",
      "description": "Edge it slides from. Values: Right | Left | Bottom."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Panel width / height. Values: Small | Medium | Large."
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "default": "'Panel'",
      "description": "Header title."
    },
    {
      "name": "hasCloseButton",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the close affordance. Values: true | false."
    },
    {
      "name": "children",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false
    },
    {
      "name": "embedded",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Render just the panel inline (no overlay/scrim) — used for documentation previews."
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": false
    }
  ],
  "EmptyState": [
    {
      "name": "icon",
      "type": "string",
      "required": false,
      "default": "'inbox'",
      "description": "Material Symbols icon name."
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "default": "'No results found'",
      "description": "Primary message."
    },
    {
      "name": "description",
      "type": "string",
      "required": false,
      "default": "'Try adjusting your filters or search terms.'",
      "description": "Supporting explanation."
    },
    {
      "name": "actionLabel",
      "type": "string",
      "required": false,
      "description": "Optional primary action label."
    },
    {
      "name": "onAction",
      "type": "() => void",
      "required": false
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Overall scale. Values: Small | Medium."
    }
  ],
  "FileUpload": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Upload files'"
    },
    {
      "name": "accept",
      "type": "string",
      "required": false,
      "description": "Accepted MIME types / extensions."
    },
    {
      "name": "multiple",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Allow multiple files. Values: true | false."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Disabled' | 'Dragging'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "helpText",
      "type": "string",
      "required": false,
      "default": "'PNG, JPG or PDF up to 10MB'",
      "description": "Constraint hint text."
    },
    {
      "name": "onFiles",
      "type": "(files: File[]) => void",
      "required": false
    }
  ],
  "FormField": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "description": "Field label text."
    },
    {
      "name": "htmlFor",
      "type": "string",
      "required": false,
      "description": "id of the wrapped control for label association."
    },
    {
      "name": "required",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Show a required asterisk. Values: true | false."
    },
    {
      "name": "helpText",
      "type": "string",
      "required": false,
      "description": "Helper text shown below the control."
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "Error message; replaces help text when present."
    },
    {
      "name": "children",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": true
    }
  ],
  "Icon": [
    {
      "name": "name",
      "type": "string",
      "required": true
    },
    {
      "name": "style",
      "type": "'outlined' | 'rounded' | 'sharp'",
      "required": false,
      "default": "'outlined'"
    },
    {
      "name": "size",
      "type": "number",
      "required": false,
      "default": "24"
    },
    {
      "name": "fill",
      "type": "0 | 1",
      "required": false,
      "default": "0"
    },
    {
      "name": "weight",
      "type": "100 | 200 | 300 | 400 | 500 | 600 | 700",
      "required": false,
      "default": "400"
    },
    {
      "name": "grade",
      "type": "0 | 200 | -25",
      "required": false,
      "default": "0"
    },
    {
      "name": "opticalSize",
      "type": "20 | 24 | 40 | 48",
      "required": false,
      "default": "24"
    },
    {
      "name": "color",
      "type": "string",
      "required": false
    },
    {
      "name": "className",
      "type": "string",
      "required": false
    },
    {
      "name": "aria-label",
      "type": "string",
      "required": false
    },
    {
      "name": "aria-hidden",
      "type": "boolean | 'true' | 'false'",
      "required": false
    }
  ],
  "Link": [
    {
      "name": "children",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Learn more'"
    },
    {
      "name": "href",
      "type": "string",
      "required": false,
      "default": "'#'"
    },
    {
      "name": "intent",
      "type": "'Default' | 'Muted'",
      "required": false,
      "default": "'Default'",
      "description": "Color emphasis. Values: Default | Muted."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Text size. Values: Small | Medium."
    },
    {
      "name": "underline",
      "type": "'None' | 'Hover' | 'Always'",
      "required": false,
      "default": "'Hover'",
      "description": "Underline behavior. Values: Always | Hover | None."
    },
    {
      "name": "external",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Open in a new tab with an icon. Values: true | false."
    },
    {
      "name": "disabled",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Non-interactive state. Values: true | false."
    },
    {
      "name": "leadingIcon",
      "type": "string",
      "required": false
    },
    {
      "name": "trailingIcon",
      "type": "string",
      "required": false
    },
    {
      "name": "onClick",
      "type": "(e: React.MouseEvent) => void",
      "required": false
    }
  ],
  "List": [
    {
      "name": "items",
      "type": "ListItem[]",
      "required": false,
      "default": "defaultItems",
      "description": "List rows."
    },
    {
      "name": "divided",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show dividers between rows. Values: true | false."
    },
    {
      "name": "interactive",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Make rows clickable. Values: true | false."
    },
    {
      "name": "size",
      "type": "'Default' | 'Compact'",
      "required": false,
      "default": "'Default'",
      "description": "Row density. Values: Compact | Default."
    },
    {
      "name": "onItemClick",
      "type": "(item: ListItem, index: number) => void",
      "required": false
    }
  ],
  "Menu": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Actions'",
      "description": "Trigger label."
    },
    {
      "name": "items",
      "type": "MenuItem[]",
      "required": false,
      "default": "sampleItems",
      "description": "Menu items."
    },
    {
      "name": "placement",
      "type": "'Bottom Start' | 'Bottom End'",
      "required": false,
      "default": "'Bottom Start'",
      "description": "Alignment to trigger. Values: Bottom Start | Bottom End."
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Open on mount. Values: true | false."
    },
    {
      "name": "forceVisible",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Always render the open menu, for documentation."
    },
    {
      "name": "onSelect",
      "type": "(label: string) => void",
      "required": false
    }
  ],
  "OtpInput": [
    {
      "name": "length",
      "type": "number",
      "required": false,
      "default": "6",
      "description": "Number of digit boxes."
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Current code value."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Focused' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false
    }
  ],
  "Pagination": [
    {
      "name": "page",
      "type": "number",
      "required": false,
      "default": "1",
      "description": "Current page (1-based)."
    },
    {
      "name": "pageCount",
      "type": "number",
      "required": false,
      "default": "10",
      "description": "Total number of pages."
    },
    {
      "name": "siblingCount",
      "type": "number",
      "required": false,
      "default": "1",
      "description": "Pages shown either side of current."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Control height. Values: Small | Medium."
    },
    {
      "name": "showEdges",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show first / last controls. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(page: number) => void",
      "required": false
    }
  ],
  "Popover": [
    {
      "name": "trigger",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false,
      "description": "Element that toggles the popover."
    },
    {
      "name": "title",
      "type": "string",
      "required": false,
      "default": "'Popover title'",
      "description": "Optional panel heading."
    },
    {
      "name": "content",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false,
      "default": "'Popover content with interactive elements.'",
      "description": "Popover body content."
    },
    {
      "name": "placement",
      "type": "'Left' | 'Right' | 'Bottom' | 'Top'",
      "required": false,
      "default": "'Bottom'",
      "description": "Position relative to the trigger. Values: Top | Bottom | Left | Right."
    },
    {
      "name": "open",
      "type": "boolean",
      "required": false
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Open on mount. Values: true | false."
    },
    {
      "name": "forceVisible",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Keep the panel visible regardless of state — used for documentation."
    },
    {
      "name": "onOpenChange",
      "type": "(open: boolean) => void",
      "required": false
    }
  ],
  "Progress": [
    {
      "name": "variant",
      "type": "'Linear' | 'Circular'",
      "required": false,
      "default": "'Linear'",
      "description": "Bar or ring. Values: Linear | Circular."
    },
    {
      "name": "value",
      "type": "number",
      "required": false,
      "default": "60",
      "description": "Completion percentage 0–100. Ignored when indeterminate."
    },
    {
      "name": "indeterminate",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Unknown-duration animation. Values: true | false."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Bar height / ring diameter. Values: Small | Medium | Large."
    },
    {
      "name": "intent",
      "type": "'Success' | 'Warning' | 'Error' | 'Primary'",
      "required": false,
      "default": "'Primary'",
      "description": "Fill color. Values: Primary | Success | Warning | Error."
    },
    {
      "name": "showValue",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Render the percentage. Values: true | false."
    }
  ],
  "RadioButton": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Radio option'"
    },
    {
      "name": "selected",
      "type": "boolean",
      "required": false,
      "description": "Selected state. Values: true | false."
    },
    {
      "name": "name",
      "type": "string",
      "required": false,
      "default": "'radio'"
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Hover' | 'Focused' | 'Pressed' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "withLabel",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Render the label. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(selected: boolean) => void",
      "required": false
    }
  ],
  "RadioGroup": [
    {
      "name": "label",
      "type": "string",
      "required": false
    },
    {
      "name": "name",
      "type": "string",
      "required": false,
      "description": "Shared input name for the group."
    },
    {
      "name": "options",
      "type": "RadioOption[]",
      "required": false,
      "default": "DEFAULT_OPTIONS",
      "description": "Radio options."
    },
    {
      "name": "value",
      "type": "string",
      "required": false,
      "description": "Selected option value."
    },
    {
      "name": "orientation",
      "type": "'Vertical' | 'Horizontal'",
      "required": false,
      "default": "'Vertical'",
      "description": "Layout direction. Values: Vertical | Horizontal."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false
    }
  ],
  "Rating": [
    {
      "name": "value",
      "type": "number",
      "required": false,
      "default": "0",
      "description": "Current rating."
    },
    {
      "name": "max",
      "type": "number",
      "required": false,
      "default": "5",
      "description": "Number of stars."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Star size. Values: Small | Medium."
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Display-only mode. Values: true | false."
    },
    {
      "name": "showValue",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Show numeric value. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(value: number) => void",
      "required": false
    }
  ],
  "SegmentedControl": [
    {
      "name": "items",
      "type": "string[]",
      "required": false,
      "default": "['Day', 'Week', 'Month']",
      "description": "Segment labels."
    },
    {
      "name": "value",
      "type": "number",
      "required": false,
      "description": "Active segment index."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Segment height. Values: Small | Medium."
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Stretch to fill the row. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(index: number) => void",
      "required": false
    }
  ],
  "Select": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Country'",
      "description": "Render the label. Values: true | false."
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "default": "'Select an option'"
    },
    {
      "name": "options",
      "type": "string[]",
      "required": false,
      "default": "defaultOptions"
    },
    {
      "name": "value",
      "type": "string",
      "required": false
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Hover' | 'Focused' | 'Disabled' | 'Open'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "widthMode",
      "type": "'Fixed' | 'Content Adaptable'",
      "required": false,
      "default": "'Fixed'",
      "description": "Trigger sizing. Values: Fixed | Content Adaptable."
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "default": "true"
    },
    {
      "name": "search",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Filterable option list. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false
    }
  ],
  "Skeleton": [
    {
      "name": "variant",
      "type": "'Text' | 'Rect' | 'Circle'",
      "required": false,
      "default": "'Text'",
      "description": "Placeholder shape. Values: Text | Rect | Circle."
    },
    {
      "name": "width",
      "type": "string | number",
      "required": false,
      "description": "Explicit width. Values: string | number."
    },
    {
      "name": "height",
      "type": "string | number",
      "required": false,
      "description": "Explicit height. Values: string | number."
    },
    {
      "name": "lines",
      "type": "number",
      "required": false,
      "default": "1",
      "description": "Number of text lines. Only applies to the Text variant."
    },
    {
      "name": "radius",
      "type": "string | number",
      "required": false
    }
  ],
  "Slider": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Value'"
    },
    {
      "name": "min",
      "type": "number",
      "required": false,
      "default": "0",
      "description": "Minimum value."
    },
    {
      "name": "max",
      "type": "number",
      "required": false,
      "default": "100",
      "description": "Maximum value."
    },
    {
      "name": "value",
      "type": "number",
      "required": false
    },
    {
      "name": "step",
      "type": "number",
      "required": false,
      "default": "1",
      "description": "Increment granularity."
    },
    {
      "name": "state",
      "type": "'Default' | 'Focused' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "showValue",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the current value. Values: true | false."
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the field label. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(value: number) => void",
      "required": false
    }
  ],
  "Snackbar": [
    {
      "name": "message",
      "type": "string",
      "required": false,
      "default": "'Assessment saved successfully.'"
    },
    {
      "name": "intent",
      "type": "'Info' | 'Success' | 'Warning' | 'Error' | 'Neutral'",
      "required": false,
      "default": "'Neutral'",
      "description": "Accent icon color. Values: Neutral | Info | Success | Warning | Error."
    },
    {
      "name": "hasAction",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Show an inline action (e.g. Undo). Values: true | false."
    },
    {
      "name": "hasClose",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the dismiss button. Values: true | false."
    },
    {
      "name": "actionLabel",
      "type": "string",
      "required": false,
      "default": "'Undo'"
    },
    {
      "name": "onAction",
      "type": "() => void",
      "required": false
    },
    {
      "name": "onClose",
      "type": "() => void",
      "required": false
    }
  ],
  "Spinner": [
    {
      "name": "size",
      "type": "'Small' | 'Medium' | 'Large'",
      "required": false,
      "default": "'Medium'",
      "description": "Diameter 16 / 24 / 40. Values: Small | Medium | Large."
    },
    {
      "name": "intent",
      "type": "'Neutral' | 'Primary' | 'Inverse'",
      "required": false,
      "default": "'Primary'",
      "description": "Arc color. Values: Primary | Neutral | Inverse."
    },
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Loading'",
      "description": "Accessible label."
    }
  ],
  "Stat": [
    {
      "name": "label",
      "type": "string",
      "required": true,
      "default": "'Average score'",
      "description": "Metric name."
    },
    {
      "name": "value",
      "type": "string | number",
      "required": true,
      "default": "'84%'",
      "description": "Metric value. Values: string | number."
    },
    {
      "name": "delta",
      "type": "string",
      "required": false,
      "default": "'+4.2%'",
      "description": "Change indicator text."
    },
    {
      "name": "deltaIntent",
      "type": "'up' | 'down' | 'neutral'",
      "required": false,
      "default": "'up'",
      "description": "Trend direction / color. Values: up | down | neutral."
    },
    {
      "name": "icon",
      "type": "string",
      "required": false,
      "description": "Optional leading icon."
    },
    {
      "name": "helpText",
      "type": "string",
      "required": false
    }
  ],
  "Stepper": [
    {
      "name": "steps",
      "type": "Step[]",
      "required": false,
      "default": "defaultSteps",
      "description": "Ordered steps."
    },
    {
      "name": "activeStep",
      "type": "number",
      "required": false,
      "default": "1",
      "description": "Zero-based index of the current step."
    },
    {
      "name": "orientation",
      "type": "'Vertical' | 'Horizontal'",
      "required": false,
      "default": "'Horizontal'",
      "description": "Layout direction. Values: Horizontal | Vertical."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Indicator size. Values: Small | Medium."
    }
  ],
  "Table": [
    {
      "name": "columns",
      "type": "TableColumn[]",
      "required": false,
      "default": "defaultColumns",
      "description": "Column definitions."
    },
    {
      "name": "rows",
      "type": "Record<string, ReactNode>[]",
      "required": false,
      "default": "defaultRows",
      "description": "Row data keyed by column."
    },
    {
      "name": "size",
      "type": "'Default' | 'Compact'",
      "required": false,
      "default": "'Default'",
      "description": "Row height density. Values: Compact | Default."
    },
    {
      "name": "striped",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Zebra-stripe rows. Values: true | false."
    },
    {
      "name": "hoverable",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Highlight rows on hover. Values: true | false."
    },
    {
      "name": "selectable",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Add a row selection column. Values: true | false."
    },
    {
      "name": "caption",
      "type": "string",
      "required": false
    },
    {
      "name": "onRowClick",
      "type": "(row: Record<string, ReactNode>, index: number) => void",
      "required": false
    }
  ],
  "Tabs": [
    {
      "name": "items",
      "type": "TabItem[]",
      "required": false,
      "default": "defaultItems"
    },
    {
      "name": "style",
      "type": "'Underline' | 'Contained'",
      "required": false,
      "default": "'Underline'",
      "description": "Visual treatment. Values: Underline | Contained."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Tab height 40 / 48. Values: Small | Medium."
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Stretch tabs to fill the row. Values: true | false."
    },
    {
      "name": "value",
      "type": "number",
      "required": false
    },
    {
      "name": "onChange",
      "type": "(index: number) => void",
      "required": false
    }
  ],
  "Tag": [
    {
      "name": "label",
      "type": "string",
      "required": true,
      "description": "Tag text."
    },
    {
      "name": "intent",
      "type": "'Info' | 'Success' | 'Warning' | 'Error' | 'Neutral'",
      "required": false,
      "default": "'Neutral'",
      "description": "Semantic color. Values: Neutral | Info | Success | Warning | Error."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Tag height. Values: Small | Medium."
    },
    {
      "name": "removable",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Show a remove affordance. Values: true | false."
    },
    {
      "name": "leadingIcon",
      "type": "string",
      "required": false,
      "description": "Optional leading icon."
    },
    {
      "name": "onRemove",
      "type": "() => void",
      "required": false
    },
    {
      "name": "onClick",
      "type": "() => void",
      "required": false
    }
  ],
  "TextInput": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Label'",
      "description": "Show the field label. Values: true | false."
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "default": "'Placeholder text'"
    },
    {
      "name": "value",
      "type": "string",
      "required": false
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Hover' | 'Focused' | 'Disabled' | 'Filled' | 'ReadOnly'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Control height. Values: Small | Medium."
    },
    {
      "name": "leadingIcon",
      "type": "string",
      "required": false,
      "description": "Show a leading icon. Values: true | false."
    },
    {
      "name": "trailingIcon",
      "type": "string",
      "required": false,
      "description": "Show a trailing icon. Values: true | false."
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "default": "true"
    },
    {
      "name": "helpText",
      "type": "string",
      "required": false,
      "description": "Show helper text. Values: true | false."
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false,
      "description": "Show error message. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false
    }
  ],
  "Textarea": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Description'"
    },
    {
      "name": "placeholder",
      "type": "string",
      "required": false,
      "default": "'Placeholder text'"
    },
    {
      "name": "value",
      "type": "string",
      "required": false
    },
    {
      "name": "rows",
      "type": "number",
      "required": false,
      "default": "4",
      "description": "Visible text rows."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Vertical padding density. Values: Small | Medium."
    },
    {
      "name": "state",
      "type": "'Error' | 'Default' | 'Hover' | 'Focused' | 'Disabled' | 'Filled' | 'ReadOnly'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "showLabel",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Show the field label. Values: true | false."
    },
    {
      "name": "helpText",
      "type": "string",
      "required": false
    },
    {
      "name": "errorText",
      "type": "string",
      "required": false
    },
    {
      "name": "maxLength",
      "type": "number",
      "required": false,
      "description": "Maximum character length."
    },
    {
      "name": "showCount",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Show character counter. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "required": false
    }
  ],
  "Toggle": [
    {
      "name": "label",
      "type": "string",
      "required": false,
      "default": "'Toggle setting'"
    },
    {
      "name": "checked",
      "type": "boolean",
      "required": false,
      "description": "On / off state. Values: true | false."
    },
    {
      "name": "state",
      "type": "'Default' | 'Hover' | 'Focused' | 'Disabled'",
      "required": false,
      "default": "'Default'",
      "description": "Forces a visual state for documentation. Omit for real interactivity."
    },
    {
      "name": "size",
      "type": "'Small' | 'Medium'",
      "required": false,
      "default": "'Medium'",
      "description": "Track / thumb size. Values: Small | Medium."
    },
    {
      "name": "withLabel",
      "type": "boolean",
      "required": false,
      "default": "true",
      "description": "Render the label. Values: true | false."
    },
    {
      "name": "onChange",
      "type": "(checked: boolean) => void",
      "required": false
    }
  ],
  "Tooltip": [
    {
      "name": "content",
      "type": "string",
      "required": false,
      "default": "'Supplementary help text'"
    },
    {
      "name": "placement",
      "type": "'Left' | 'Right' | 'Bottom' | 'Top'",
      "required": false,
      "default": "'Top'",
      "description": "Position relative to the trigger. Values: Top | Bottom | Left | Right."
    },
    {
      "name": "theme",
      "type": "'Light' | 'Dark'",
      "required": false,
      "default": "'Dark'",
      "description": "Surface color. Values: Light | Dark."
    },
    {
      "name": "type",
      "type": "'Default' | 'Accessibility'",
      "required": false,
      "default": "'Default'",
      "description": "Accessibility type uses larger text. Values: Default | Accessibility."
    },
    {
      "name": "children",
      "type": "string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | Promise<string | number | bigint | boolean | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactPortal | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').ReactElement<unknown, string | import('/Users/inspera/Documents/Working Mockups/Component Library V2/node_modules/.pnpm/@types+react@19.2.14/node_modules/@types/react/index').JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | null",
      "required": false
    },
    {
      "name": "forceVisible",
      "type": "boolean",
      "required": false,
      "default": "false",
      "description": "Keep the tooltip visible regardless of hover — used for documentation."
    }
  ]
}
