// GENERATED by scripts/build-portable.ts from the component TypeScript
// interfaces. Do not edit. Regenerate with `pnpm generate`.

import type { ComponentApi, PropDoc } from '../../scripts/extract-props'

export type { ComponentApi, PropDoc }

export const componentApi: Record<string, ComponentApi> = {
  "Accordion": {
    "props": [
      {
        "name": "items",
        "type": "AccordionItem[]",
        "required": false,
        "default": "defaultItems",
        "description": "Accordion sections."
      },
      {
        "name": "type",
        "type": "'Single' | 'Multiple'",
        "required": false,
        "default": "'Single'",
        "description": "Allow one or many open at once."
      },
      {
        "name": "defaultOpenIndex",
        "type": "number",
        "required": false,
        "default": "0",
        "description": "Initially open section."
      },
      {
        "name": "iconPosition",
        "type": "'Left' | 'Right'",
        "required": false,
        "default": "'Right'",
        "description": "Chevron placement."
      }
    ],
    "relatedTypes": {
      "AccordionItem": "export interface AccordionItem {\n  title: string\n  content: ReactNode\n}"
    }
  },
  "Alert": {
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "'Heads up'",
        "description": "Short headline stating what happened."
      },
      {
        "name": "message",
        "type": "string",
        "required": false,
        "default": "'This is a contextual inline message that matches the intent severity.'",
        "description": "Supporting detail. Keep it to one or two sentences."
      },
      {
        "name": "intent",
        "type": "'Info' | 'Success' | 'Warning' | 'Error'",
        "required": false,
        "default": "'Info'",
        "description": "Severity / color."
      },
      {
        "name": "layout",
        "type": "'Simple' | 'With CTA' | 'With Close' | 'With CTA + Close'",
        "required": false,
        "default": "'Simple'",
        "description": "Action affordances."
      },
      {
        "name": "background",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Tinted fill vs. left-accent only."
      },
      {
        "name": "ctaLabel",
        "type": "string",
        "required": false,
        "default": "'View details'",
        "description": "Label for the inline action. Only rendered by the \"With CTA\" layouts."
      },
      {
        "name": "onCta",
        "type": "() => void",
        "required": false,
        "description": "Fired when the inline action is activated."
      },
      {
        "name": "onClose",
        "type": "() => void",
        "required": false,
        "description": "Fired when the alert is dismissed. Only rendered by the \"With Close\" layouts."
      }
    ],
    "relatedTypes": {}
  },
  "Avatar": {
    "props": [
      {
        "name": "size",
        "type": "'Small' | 'Medium' | 'Large'",
        "required": false,
        "default": "'Medium'",
        "description": "Diameter 32 / 40 / 56."
      },
      {
        "name": "content",
        "type": "'Image' | 'Initials' | 'Icon'",
        "required": false,
        "default": "'Initials'",
        "description": "What fills the avatar."
      },
      {
        "name": "status",
        "type": "'None' | 'Online' | 'Offline' | 'Busy'",
        "required": false,
        "default": "'None'",
        "description": "Presence indicator dot."
      },
      {
        "name": "initials",
        "type": "string",
        "required": false,
        "default": "'JC'",
        "description": "One or two letters, used when content is Initials. Derive from the name rather than asking for them."
      },
      {
        "name": "imageSrc",
        "type": "string",
        "required": false,
        "default": "'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=112&h=112&fit=crop&auto=format'",
        "description": "Image URL, used when content is Image. Falls back to initials if it fails to load."
      },
      {
        "name": "alt",
        "type": "string",
        "required": false,
        "default": "'User avatar'",
        "description": "Alternative text for the image. Required whenever an image is shown."
      },
      {
        "name": "icon",
        "type": "string",
        "required": false,
        "default": "'person'",
        "description": "Material Symbols name, used when content is Icon."
      }
    ],
    "relatedTypes": {}
  },
  "AvatarGroup": {
    "props": [
      {
        "name": "avatars",
        "type": "AvatarGroupItem[]",
        "required": false,
        "default": "defaultAvatars",
        "description": "Avatars to display."
      },
      {
        "name": "max",
        "type": "number",
        "required": false,
        "default": "4",
        "description": "Maximum shown before overflow."
      },
      {
        "name": "size",
        "type": "AvatarSize",
        "required": false,
        "default": "'Medium'",
        "description": "Avatar diameter."
      }
    ],
    "relatedTypes": {
      "AvatarGroupItem": "export interface AvatarGroupItem {\n  content?: AvatarContent\n  name?: string\n}"
    }
  },
  "Badge": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Badge'",
        "description": "The badge text. One or two words."
      },
      {
        "name": "intent",
        "type": "'Neutral' | 'Info' | 'Success' | 'Warning' | 'Error'",
        "required": false,
        "default": "'Neutral'",
        "description": "Semantic color."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Height 20 / 24."
      },
      {
        "name": "withIcon",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Show a leading status icon."
      },
      {
        "name": "icon",
        "type": "string",
        "required": false,
        "description": "Material Symbols name shown before the label when withIcon is set."
      }
    ],
    "relatedTypes": {}
  },
  "Breadcrumb": {
    "props": [
      {
        "name": "items",
        "type": "string[]",
        "required": false,
        "default": "defaultItems",
        "description": "Trail from root to current page. The last entry is the current page and is not a link."
      },
      {
        "name": "separator",
        "type": "'Slash' | 'Chevron'",
        "required": false,
        "default": "'Chevron'",
        "description": "Divider glyph between items."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Text size 14 / 16."
      },
      {
        "name": "onNavigate",
        "type": "(index: number) => void",
        "required": false,
        "description": "Fired with the index of the crumb that was clicked."
      }
    ],
    "relatedTypes": {}
  },
  "Button": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Button'",
        "description": "The button text. Start with a verb — \"Save\", not \"OK\"."
      },
      {
        "name": "intent",
        "type": "'Primary' | 'Secondary' | 'Outline' | 'Text' | 'Success' | 'Warning' | 'Destructive'",
        "required": false,
        "default": "'Primary'",
        "description": "Visual role / semantic weight."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium' | 'Large'",
        "required": false,
        "default": "'Medium'",
        "description": "Height 32 / 40 / 48."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Pressed' | 'Disabled'",
        "required": false,
        "description": "Freezes a visual state so documentation can show it without a pointer. Leave unset in application code — hover, focus and active are handled in CSS and work on their own."
      },
      {
        "name": "content",
        "type": "'Text' | 'Icon + Text' | 'Text + Icon' | 'Text + Disclosure'",
        "required": false,
        "default": "'Text'",
        "description": "Label / icon composition."
      },
      {
        "name": "icon",
        "type": "string",
        "required": false,
        "default": "'add'",
        "description": "Material Symbols name. Only rendered by the icon-bearing content variants."
      },
      {
        "name": "onClick",
        "type": "() => void",
        "required": false,
        "description": "Fired on click and on Enter or Space."
      }
    ],
    "relatedTypes": {}
  },
  "Card": {
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "'Card title'",
        "description": "Optional heading for the card."
      },
      {
        "name": "body",
        "type": "string",
        "required": false,
        "default": "'Group related content in a contained surface using consistent padding and elevation.'",
        "description": "Short body copy. For anything richer, pass children instead."
      },
      {
        "name": "elevation",
        "type": "'Flat' | 'Raised' | 'Outlined'",
        "required": false,
        "default": "'Raised'",
        "description": "Surface treatment."
      },
      {
        "name": "padding",
        "type": "'Compact' | 'Default' | 'Spacious'",
        "required": false,
        "default": "'Default'",
        "description": "Internal padding (12 / 16 / 24)."
      },
      {
        "name": "interactive",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Renders as a focusable button with hover elevation."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "Card contents. Takes precedence over title and body."
      },
      {
        "name": "onClick",
        "type": "() => void",
        "required": false,
        "description": "Fired when an interactive card is activated. Set interactive as well, or there is no affordance."
      }
    ],
    "relatedTypes": {}
  },
  "Checkbox": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Checkbox label'",
        "description": "Text beside the box. Always provide one."
      },
      {
        "name": "checked",
        "type": "boolean",
        "required": false,
        "description": "Checked state."
      },
      {
        "name": "indeterminate",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Partially-selected state, for a parent whose children are mixed. Wins over `checked` visually and announces as `aria-checked=\"mixed\"`."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Pressed' | 'Disabled' | 'Error'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Hover`, `Focused` and `Pressed` are presentation-only — leave them unset in application code, where CSS drives them from the real pointer and keyboard. `Error` and `Disabled` are real application state and belong in your code."
      },
      {
        "name": "withLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Render the label."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Indicator size."
      },
      {
        "name": "onChange",
        "type": "(checked: boolean) => void",
        "required": false,
        "description": "Fired with the new checked state."
      }
    ],
    "relatedTypes": {}
  },
  "CheckboxGroup": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Group label, announced as the fieldset legend."
      },
      {
        "name": "options",
        "type": "CheckboxOption[]",
        "required": false,
        "default": "DEFAULT_OPTIONS",
        "description": "Checkbox options."
      },
      {
        "name": "value",
        "type": "string[]",
        "required": false,
        "description": "Selected option values."
      },
      {
        "name": "orientation",
        "type": "'Vertical' | 'Horizontal'",
        "required": false,
        "default": "'Vertical'",
        "description": "Layout direction."
      },
      {
        "name": "state",
        "type": "'Default' | 'Disabled' | 'Error'",
        "required": false,
        "default": "'Default'",
        "description": "Forces a visual state for documentation. Omit for real interactivity."
      },
      {
        "name": "onChange",
        "type": "(value: string[]) => void",
        "required": false,
        "description": "Fired with the full array of selected values."
      }
    ],
    "relatedTypes": {
      "CheckboxOption": "export interface CheckboxOption {\n  label: string\n  value: string\n}"
    }
  },
  "DatePicker": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Date'",
        "description": "Field label."
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "Selected date (YYYY-MM-DD)."
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "'Select date'",
        "description": "Trigger placeholder."
      },
      {
        "name": "state",
        "type": "'Default' | 'Focused' | 'Disabled' | 'Error'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Focused` is presentation-only — leave it unset in application code, where CSS drives it from the real pointer and keyboard. `Error` and `Disabled` are real application state and belong in your code."
      },
      {
        "name": "showLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the field label."
      },
      {
        "name": "defaultOpen",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Open the calendar initially."
      },
      {
        "name": "onChange",
        "type": "(iso: string) => void",
        "required": false,
        "description": "Fired with the selected date as an ISO string (YYYY-MM-DD)."
      }
    ],
    "relatedTypes": {}
  },
  "Dialog": {
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "'Dialog title'",
        "description": "Dialog heading. Also the accessible name."
      },
      {
        "name": "body",
        "type": "ReactNode",
        "required": false,
        "default": "'This is the dialog body. Provide context or a clear description of the action the user is about to take.'",
        "description": "Dialog content."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium' | 'Large'",
        "required": false,
        "default": "'Medium'",
        "description": "Panel width 400 / 480 / 560."
      },
      {
        "name": "hasCloseButton",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the header close affordance."
      },
      {
        "name": "hasActions",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the footer action buttons."
      },
      {
        "name": "confirmLabel",
        "type": "string",
        "required": false,
        "default": "'Continue'",
        "description": "Label for the confirming action. Name the action — \"Delete\", not \"OK\"."
      },
      {
        "name": "cancelLabel",
        "type": "string",
        "required": false,
        "default": "'Cancel'",
        "description": "Label for the dismissing action."
      },
      {
        "name": "open",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Whether the dialog is shown. Controlled — pair with onClose."
      },
      {
        "name": "embedded",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Render just the panel (no overlay) — used for documentation previews."
      },
      {
        "name": "onClose",
        "type": "() => void",
        "required": false,
        "description": "Fired on the close button, the overlay, and Escape."
      },
      {
        "name": "onConfirm",
        "type": "() => void",
        "required": false,
        "description": "Fired when the confirming action is activated."
      }
    ],
    "relatedTypes": {}
  },
  "Divider": {
    "props": [
      {
        "name": "orientation",
        "type": "'Horizontal' | 'Vertical'",
        "required": false,
        "default": "'Horizontal'",
        "description": "Divider direction."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Optional centered label (horizontal only)."
      },
      {
        "name": "spacing",
        "type": "'Compact' | 'Default' | 'Spacious'",
        "required": false,
        "default": "'Default'",
        "description": "Surrounding margin."
      }
    ],
    "relatedTypes": {}
  },
  "Drawer": {
    "props": [
      {
        "name": "open",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Visibility."
      },
      {
        "name": "side",
        "type": "'Right' | 'Left' | 'Bottom'",
        "required": false,
        "default": "'Right'",
        "description": "Edge it slides from."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium' | 'Large'",
        "required": false,
        "default": "'Medium'",
        "description": "Panel width / height."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "'Panel'",
        "description": "Header title."
      },
      {
        "name": "hasCloseButton",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the close affordance."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "Panel contents."
      },
      {
        "name": "embedded",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Render just the panel inline (no overlay/scrim) — used for documentation previews."
      },
      {
        "name": "onClose",
        "type": "() => void",
        "required": false,
        "description": "Fired on the close button, the scrim, and Escape."
      }
    ],
    "relatedTypes": {}
  },
  "EmptyState": {
    "props": [
      {
        "name": "icon",
        "type": "string",
        "required": false,
        "default": "'inbox'",
        "description": "Material Symbols icon name."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "'No results found'",
        "description": "Primary message."
      },
      {
        "name": "description",
        "type": "string",
        "required": false,
        "default": "'Try adjusting your filters or search terms.'",
        "description": "Supporting explanation."
      },
      {
        "name": "actionLabel",
        "type": "string",
        "required": false,
        "description": "Optional primary action label."
      },
      {
        "name": "onAction",
        "type": "() => void",
        "required": false,
        "description": "Fired when the action is activated. Only rendered when actionLabel is set."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Overall scale."
      }
    ],
    "relatedTypes": {}
  },
  "FileUpload": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Upload files'",
        "description": "Field label describing what to upload."
      },
      {
        "name": "accept",
        "type": "string",
        "required": false,
        "description": "Accepted MIME types / extensions."
      },
      {
        "name": "multiple",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Allow multiple files."
      },
      {
        "name": "state",
        "type": "'Default' | 'Dragging' | 'Disabled' | 'Error'",
        "required": false,
        "default": "'Default'",
        "description": "Forces a visual state for documentation. Omit for real interactivity."
      },
      {
        "name": "helpText",
        "type": "string",
        "required": false,
        "default": "'PNG, JPG or PDF up to 10MB'",
        "description": "Constraint hint text."
      },
      {
        "name": "onFiles",
        "type": "(files: File[]) => void",
        "required": false,
        "description": "Fired with the selected files, from both drop and browse."
      }
    ],
    "relatedTypes": {}
  },
  "FormField": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Field label text."
      },
      {
        "name": "htmlFor",
        "type": "string",
        "required": false,
        "description": "id of the wrapped control for label association."
      },
      {
        "name": "required",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Show a required asterisk."
      },
      {
        "name": "helpText",
        "type": "string",
        "required": false,
        "description": "Helper text shown below the control."
      },
      {
        "name": "errorText",
        "type": "string",
        "required": false,
        "description": "Error message; replaces help text when present."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": true,
        "description": "The control this field wraps. Exactly one."
      }
    ],
    "relatedTypes": {}
  },
  "Icon": {
    "props": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Material Symbols ligature name, e.g. \"search\" or \"check_circle\"."
      },
      {
        "name": "style",
        "type": "'outlined' | 'rounded' | 'sharp'",
        "required": false,
        "default": "'outlined'",
        "description": "Which Material Symbols face to use."
      },
      {
        "name": "size",
        "type": "number",
        "required": false,
        "default": "24",
        "description": "Rendered size in px. 16 compact, 20 in controls, 24 standalone."
      },
      {
        "name": "fill",
        "type": "0 | 1",
        "required": false,
        "default": "0",
        "description": "Filled (1) or outlined (0). Filled reads as a status glyph."
      },
      {
        "name": "weight",
        "type": "100 | 200 | 300 | 400 | 500 | 600 | 700",
        "required": false,
        "default": "400",
        "description": "Stroke weight. 400 matches body text."
      },
      {
        "name": "grade",
        "type": "-25 | 0 | 200",
        "required": false,
        "default": "0",
        "description": "Optical grade. Use 200 on dark backgrounds to hold weight."
      },
      {
        "name": "opticalSize",
        "type": "20 | 24 | 40 | 48",
        "required": false,
        "default": "24",
        "description": "Optical size axis. Match to the rendered size."
      },
      {
        "name": "color",
        "type": "string",
        "required": false,
        "description": "Icon colour. Defaults to currentColor so it inherits from text."
      },
      {
        "name": "className",
        "type": "string",
        "required": false,
        "description": "Additional classes, merged with the Material Symbols class."
      },
      {
        "name": "aria-label",
        "type": "string",
        "required": false,
        "description": "Accessible name. Required when the icon carries meaning on its own."
      },
      {
        "name": "aria-hidden",
        "type": "boolean | 'true' | 'false'",
        "required": false,
        "description": "Hides the icon from assistive technology. Defaults to true unless aria-label is set."
      }
    ],
    "relatedTypes": {}
  },
  "Link": {
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "Link text. Takes precedence over label."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Learn more'",
        "description": "Link text, when not passing children."
      },
      {
        "name": "href",
        "type": "string",
        "required": false,
        "default": "'#'",
        "description": "Destination URL. Always provide a real one."
      },
      {
        "name": "intent",
        "type": "'Default' | 'Muted'",
        "required": false,
        "default": "'Default'",
        "description": "Color emphasis."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Text size."
      },
      {
        "name": "underline",
        "type": "'Always' | 'Hover' | 'None'",
        "required": false,
        "default": "'Hover'",
        "description": "Underline behavior."
      },
      {
        "name": "external",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Open in a new tab with an icon."
      },
      {
        "name": "disabled",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Non-interactive state."
      },
      {
        "name": "leadingIcon",
        "type": "string",
        "required": false,
        "description": "Material Symbols name shown before the text."
      },
      {
        "name": "trailingIcon",
        "type": "string",
        "required": false,
        "description": "Material Symbols name shown after the text."
      },
      {
        "name": "onClick",
        "type": "(e: React.MouseEvent) => void",
        "required": false,
        "description": "Fired on activation. Use for routing, not to replace href."
      }
    ],
    "relatedTypes": {}
  },
  "List": {
    "props": [
      {
        "name": "items",
        "type": "ListItem[]",
        "required": false,
        "default": "defaultItems",
        "description": "List rows."
      },
      {
        "name": "divided",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show dividers between rows."
      },
      {
        "name": "interactive",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Make rows clickable."
      },
      {
        "name": "size",
        "type": "'Compact' | 'Default'",
        "required": false,
        "default": "'Default'",
        "description": "Row density."
      },
      {
        "name": "onItemClick",
        "type": "(item: ListItem, index: number) => void",
        "required": false,
        "description": "Fired with the item and its index. Set interactive as well."
      }
    ],
    "relatedTypes": {
      "ListItem": "export interface ListItem {\n  primary: string\n  secondary?: string\n  leading?: ReactNode\n  trailing?: ReactNode\n}"
    }
  },
  "Menu": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Actions'",
        "description": "Trigger label."
      },
      {
        "name": "items",
        "type": "MenuItem[]",
        "required": false,
        "default": "sampleItems",
        "description": "Menu items."
      },
      {
        "name": "placement",
        "type": "'Bottom Start' | 'Bottom End'",
        "required": false,
        "default": "'Bottom Start'",
        "description": "Alignment to trigger."
      },
      {
        "name": "open",
        "type": "boolean",
        "required": false,
        "description": "Controlled open state. Leave unset to let the menu manage itself."
      },
      {
        "name": "defaultOpen",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Open on mount."
      },
      {
        "name": "forceVisible",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Always render the open menu, for documentation."
      },
      {
        "name": "onSelect",
        "type": "(label: string) => void",
        "required": false,
        "description": "Fired with the label of the chosen item."
      }
    ],
    "relatedTypes": {
      "MenuItem": "export interface MenuItem {\n  label: string\n  icon?: string\n  danger?: boolean\n  disabled?: boolean\n  divider?: boolean\n}"
    }
  },
  "OtpInput": {
    "props": [
      {
        "name": "length",
        "type": "number",
        "required": false,
        "default": "6",
        "description": "Number of digit boxes."
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "Current code value."
      },
      {
        "name": "state",
        "type": "'Default' | 'Focused' | 'Error' | 'Disabled'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Focused` is presentation-only — leave it unset in application code, where CSS drives it from the real pointer and keyboard. `Error` and `Disabled` are real application state and belong in your code."
      },
      {
        "name": "onChange",
        "type": "(value: string) => void",
        "required": false,
        "description": "Fired with the full code as digits are entered or pasted."
      }
    ],
    "relatedTypes": {}
  },
  "Pagination": {
    "props": [
      {
        "name": "page",
        "type": "number",
        "required": false,
        "default": "1",
        "description": "Current page (1-based)."
      },
      {
        "name": "pageCount",
        "type": "number",
        "required": false,
        "default": "10",
        "description": "Total number of pages."
      },
      {
        "name": "siblingCount",
        "type": "number",
        "required": false,
        "default": "1",
        "description": "Pages shown either side of current."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Control height."
      },
      {
        "name": "showEdges",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show first / last controls."
      },
      {
        "name": "onChange",
        "type": "(page: number) => void",
        "required": false,
        "description": "Fired with the requested page number, 1-based."
      }
    ],
    "relatedTypes": {}
  },
  "Popover": {
    "props": [
      {
        "name": "trigger",
        "type": "ReactNode",
        "required": false,
        "description": "Element that toggles the popover."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "default": "'Popover title'",
        "description": "Optional panel heading."
      },
      {
        "name": "content",
        "type": "ReactNode",
        "required": false,
        "default": "'Popover content with interactive elements.'",
        "description": "Popover body content."
      },
      {
        "name": "placement",
        "type": "'Top' | 'Bottom' | 'Left' | 'Right'",
        "required": false,
        "default": "'Bottom'",
        "description": "Position relative to the trigger."
      },
      {
        "name": "open",
        "type": "boolean",
        "required": false,
        "description": "Controlled open state. Leave unset to let the popover manage itself."
      },
      {
        "name": "defaultOpen",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Open on mount."
      },
      {
        "name": "forceVisible",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Keep the panel visible regardless of state — used for documentation."
      },
      {
        "name": "onOpenChange",
        "type": "(open: boolean) => void",
        "required": false,
        "description": "Fired when the popover opens or closes."
      }
    ],
    "relatedTypes": {}
  },
  "Progress": {
    "props": [
      {
        "name": "variant",
        "type": "'Linear' | 'Circular'",
        "required": false,
        "default": "'Linear'",
        "description": "Bar or ring."
      },
      {
        "name": "value",
        "type": "number",
        "required": false,
        "default": "60",
        "description": "Completion percentage 0–100. Ignored when indeterminate."
      },
      {
        "name": "indeterminate",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Unknown-duration animation."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium' | 'Large'",
        "required": false,
        "default": "'Medium'",
        "description": "Bar height / ring diameter."
      },
      {
        "name": "intent",
        "type": "'Primary' | 'Success' | 'Warning' | 'Error'",
        "required": false,
        "default": "'Primary'",
        "description": "Fill color."
      },
      {
        "name": "showValue",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Render the percentage."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Progress'",
        "description": "Accessible name. Say what is progressing, not just \"Progress\"."
      }
    ],
    "relatedTypes": {}
  },
  "RadioButton": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Radio option'",
        "description": "Text beside the control. Always provide one."
      },
      {
        "name": "selected",
        "type": "boolean",
        "required": false,
        "description": "Selected state."
      },
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Shared form name. Every radio in a group must use the same value. Left unset, each radio gets its own generated name and stands alone — this used to default to the literal `\"radio\"`, which silently put every unrelated RadioButton on a page into one mutually exclusive group."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Pressed' | 'Disabled' | 'Error'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Hover`, `Focused` and `Pressed` are presentation-only — leave them unset in application code, where CSS drives them from the real pointer and keyboard. `Error` and `Disabled` are real application state and belong in your code."
      },
      {
        "name": "withLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Render the label."
      },
      {
        "name": "onChange",
        "type": "(selected: boolean) => void",
        "required": false,
        "description": "Fired when this option becomes selected."
      }
    ],
    "relatedTypes": {}
  },
  "RadioGroup": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "Group label, announced as the radiogroup name."
      },
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Shared input name for the group."
      },
      {
        "name": "options",
        "type": "RadioOption[]",
        "required": false,
        "default": "DEFAULT_OPTIONS",
        "description": "Radio options."
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "Selected option value."
      },
      {
        "name": "orientation",
        "type": "'Vertical' | 'Horizontal'",
        "required": false,
        "default": "'Vertical'",
        "description": "Layout direction."
      },
      {
        "name": "state",
        "type": "'Default' | 'Disabled' | 'Error'",
        "required": false,
        "default": "'Default'",
        "description": "Forces a visual state for documentation. Omit for real interactivity."
      },
      {
        "name": "onChange",
        "type": "(value: string) => void",
        "required": false,
        "description": "Fired with the newly selected value."
      }
    ],
    "relatedTypes": {
      "RadioOption": "export interface RadioOption {\n  label: string\n  value: string\n}"
    }
  },
  "Rating": {
    "props": [
      {
        "name": "value",
        "type": "number",
        "required": false,
        "description": "Current rating. Controlled — pair with onChange. Omit it and the component tracks its own, the same contract Checkbox and Toggle use."
      },
      {
        "name": "max",
        "type": "number",
        "required": false,
        "default": "5",
        "description": "Number of stars."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Star size."
      },
      {
        "name": "readOnly",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Display-only mode."
      },
      {
        "name": "showValue",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Show numeric value."
      },
      {
        "name": "onChange",
        "type": "(value: number) => void",
        "required": false,
        "description": "Fired with the chosen rating. Not fired when readOnly."
      }
    ],
    "relatedTypes": {}
  },
  "SegmentedControl": {
    "props": [
      {
        "name": "items",
        "type": "string[]",
        "required": false,
        "default": "['Day', 'Week', 'Month']",
        "description": "Segment labels."
      },
      {
        "name": "value",
        "type": "number",
        "required": false,
        "description": "Active segment index."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Segment height."
      },
      {
        "name": "fullWidth",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Stretch to fill the row."
      },
      {
        "name": "onChange",
        "type": "(index: number) => void",
        "required": false,
        "description": "Fired with the index of the chosen segment."
      }
    ],
    "relatedTypes": {}
  },
  "Select": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Country'",
        "description": "Render the label."
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "'Select an option'",
        "description": "Shown when nothing is selected. Not a substitute for the label."
      },
      {
        "name": "options",
        "type": "string[]",
        "required": false,
        "default": "defaultOptions",
        "description": "The selectable values, in the order they should appear."
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "Selected value. Controlled — pair with onChange."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Disabled' | 'Error' | 'Open'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Hover`, `Focused` and `Open` are presentation-only — leave them unset in application code, where CSS and the component's own state drive them. `Error` and `Disabled` are real application state and belong in your code."
      },
      {
        "name": "widthMode",
        "type": "'Fixed' | 'Content Adaptable'",
        "required": false,
        "default": "'Fixed'",
        "description": "Trigger sizing."
      },
      {
        "name": "showLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Render the visible label. Hiding it still requires an accessible name."
      },
      {
        "name": "search",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Filterable option list."
      },
      {
        "name": "onChange",
        "type": "(value: string) => void",
        "required": false,
        "description": "Fired with the selected value."
      }
    ],
    "relatedTypes": {}
  },
  "Skeleton": {
    "props": [
      {
        "name": "variant",
        "type": "'Text' | 'Rect' | 'Circle'",
        "required": false,
        "default": "'Text'",
        "description": "Placeholder shape."
      },
      {
        "name": "width",
        "type": "string | number",
        "required": false,
        "description": "Explicit width."
      },
      {
        "name": "height",
        "type": "string | number",
        "required": false,
        "description": "Explicit height."
      },
      {
        "name": "lines",
        "type": "number",
        "required": false,
        "default": "1",
        "description": "Number of text lines. Only applies to the Text variant."
      },
      {
        "name": "radius",
        "type": "string | number",
        "required": false,
        "description": "Corner radius override. Match the shape being stood in for."
      }
    ],
    "relatedTypes": {}
  },
  "Slider": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Value'",
        "description": "Field label describing what is being adjusted."
      },
      {
        "name": "min",
        "type": "number",
        "required": false,
        "default": "0",
        "description": "Minimum value."
      },
      {
        "name": "max",
        "type": "number",
        "required": false,
        "default": "100",
        "description": "Maximum value."
      },
      {
        "name": "value",
        "type": "number",
        "required": false,
        "description": "Current value. Controlled — pair with onChange."
      },
      {
        "name": "step",
        "type": "number",
        "required": false,
        "default": "1",
        "description": "Increment granularity."
      },
      {
        "name": "state",
        "type": "'Default' | 'Focused' | 'Disabled'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Focused` is presentation-only — leave it unset in application code, where CSS drives it from the real pointer and keyboard. `Disabled` is real application state and belongs in your code."
      },
      {
        "name": "showValue",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the current value."
      },
      {
        "name": "showLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the field label."
      },
      {
        "name": "onChange",
        "type": "(value: number) => void",
        "required": false,
        "description": "Fired as the value changes, by drag or arrow key."
      }
    ],
    "relatedTypes": {}
  },
  "Snackbar": {
    "props": [
      {
        "name": "message",
        "type": "string",
        "required": false,
        "default": "'Assessment saved successfully.'",
        "description": "What happened. One short sentence."
      },
      {
        "name": "intent",
        "type": "'Neutral' | 'Info' | 'Success' | 'Warning' | 'Error'",
        "required": false,
        "default": "'Neutral'",
        "description": "Accent icon color."
      },
      {
        "name": "hasAction",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Show an inline action (e.g. Undo)."
      },
      {
        "name": "hasClose",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the dismiss button."
      },
      {
        "name": "actionLabel",
        "type": "string",
        "required": false,
        "default": "'Undo'",
        "description": "Label for the inline action, typically \"Undo\"."
      },
      {
        "name": "onAction",
        "type": "() => void",
        "required": false,
        "description": "Fired when the inline action is activated."
      },
      {
        "name": "onClose",
        "type": "() => void",
        "required": false,
        "description": "Fired when dismissed."
      }
    ],
    "relatedTypes": {}
  },
  "Spinner": {
    "props": [
      {
        "name": "size",
        "type": "'Small' | 'Medium' | 'Large'",
        "required": false,
        "default": "'Medium'",
        "description": "Diameter 16 / 24 / 40."
      },
      {
        "name": "intent",
        "type": "'Primary' | 'Neutral' | 'Inverse'",
        "required": false,
        "default": "'Primary'",
        "description": "Arc color."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Loading'",
        "description": "Accessible label."
      }
    ],
    "relatedTypes": {}
  },
  "Stat": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "default": "'Average score'",
        "description": "Metric name."
      },
      {
        "name": "value",
        "type": "string | number",
        "required": true,
        "default": "'84%'",
        "description": "Metric value."
      },
      {
        "name": "delta",
        "type": "string",
        "required": false,
        "default": "'+4.2%'",
        "description": "Change indicator text."
      },
      {
        "name": "deltaIntent",
        "type": "'up' | 'down' | 'neutral'",
        "required": false,
        "default": "'up'",
        "description": "Trend direction / color."
      },
      {
        "name": "icon",
        "type": "string",
        "required": false,
        "description": "Optional leading icon."
      },
      {
        "name": "helpText",
        "type": "string",
        "required": false,
        "description": "Optional context below the value, such as the comparison period."
      }
    ],
    "relatedTypes": {}
  },
  "Stepper": {
    "props": [
      {
        "name": "steps",
        "type": "Step[]",
        "required": false,
        "default": "defaultSteps",
        "description": "Ordered steps."
      },
      {
        "name": "activeStep",
        "type": "number",
        "required": false,
        "default": "1",
        "description": "Zero-based index of the current step."
      },
      {
        "name": "orientation",
        "type": "'Horizontal' | 'Vertical'",
        "required": false,
        "default": "'Horizontal'",
        "description": "Layout direction."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Indicator size."
      }
    ],
    "relatedTypes": {
      "Step": "export interface Step {\n  label: string\n  description?: string\n}"
    }
  },
  "Table": {
    "props": [
      {
        "name": "columns",
        "type": "TableColumn[]",
        "required": false,
        "default": "defaultColumns",
        "description": "Column definitions."
      },
      {
        "name": "rows",
        "type": "Record<string, ReactNode>[]",
        "required": false,
        "default": "defaultRows",
        "description": "Row data keyed by column."
      },
      {
        "name": "size",
        "type": "'Compact' | 'Default'",
        "required": false,
        "default": "'Default'",
        "description": "Row height density."
      },
      {
        "name": "striped",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Zebra-stripe rows."
      },
      {
        "name": "hoverable",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Highlight rows on hover."
      },
      {
        "name": "selectable",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Add a row selection column."
      },
      {
        "name": "caption",
        "type": "string",
        "required": false,
        "description": "Describes the table for screen readers. Provide one unless a heading already names it."
      },
      {
        "name": "onRowClick",
        "type": "(row: Record<string, ReactNode>, index: number) => void",
        "required": false,
        "description": "Fired with the row data and its index."
      }
    ],
    "relatedTypes": {
      "TableColumn": "export interface TableColumn {\n  key: string\n  header: string\n  align?: 'left' | 'right' | 'center'\n  width?: string | number\n}"
    }
  },
  "Tabs": {
    "props": [
      {
        "name": "items",
        "type": "TabItem[]",
        "required": false,
        "default": "defaultItems",
        "description": "The tabs, in order."
      },
      {
        "name": "style",
        "type": "'Underline' | 'Contained'",
        "required": false,
        "default": "'Underline'",
        "description": "Visual treatment."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Tab height 40 / 48."
      },
      {
        "name": "fullWidth",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Stretch tabs to fill the row."
      },
      {
        "name": "value",
        "type": "number",
        "required": false,
        "description": "Index of the active tab. Controlled — pair with onChange."
      },
      {
        "name": "onChange",
        "type": "(index: number) => void",
        "required": false,
        "description": "Fired with the index of the newly selected tab."
      }
    ],
    "relatedTypes": {
      "TabItem": "export interface TabItem {\n  label: string\n  icon?: string\n}"
    }
  },
  "Tag": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "Tag text."
      },
      {
        "name": "intent",
        "type": "'Neutral' | 'Info' | 'Success' | 'Warning' | 'Error'",
        "required": false,
        "default": "'Neutral'",
        "description": "Semantic color."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Tag height."
      },
      {
        "name": "removable",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Show a remove affordance."
      },
      {
        "name": "leadingIcon",
        "type": "string",
        "required": false,
        "description": "Optional leading icon."
      },
      {
        "name": "onRemove",
        "type": "() => void",
        "required": false,
        "description": "Fired when the remove control is activated. Set removable as well."
      },
      {
        "name": "onClick",
        "type": "() => void",
        "required": false,
        "description": "Fired when the tag itself is activated."
      }
    ],
    "relatedTypes": {}
  },
  "TextInput": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Label'",
        "description": "Show the field label."
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "'Placeholder text'",
        "description": "Hint shown when empty. Not a substitute for the label."
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "Current value. Controlled — pair with onChange."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Disabled' | 'Error' | 'Filled' | 'ReadOnly'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Hover`, `Focused` and `Filled` are presentation-only — leave them unset in application code, where CSS drives them from the real pointer and keyboard. `Error`, `Disabled` and `ReadOnly` are real application state and belong in your code."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Control height."
      },
      {
        "name": "leadingIcon",
        "type": "string",
        "required": false,
        "description": "Show a leading icon."
      },
      {
        "name": "trailingIcon",
        "type": "string",
        "required": false,
        "description": "Show a trailing icon."
      },
      {
        "name": "showLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Render the visible label. Hiding it still requires an accessible name."
      },
      {
        "name": "helpText",
        "type": "string",
        "required": false,
        "description": "Show helper text."
      },
      {
        "name": "errorText",
        "type": "string",
        "required": false,
        "description": "Show error message."
      },
      {
        "name": "onChange",
        "type": "(value: string) => void",
        "required": false,
        "description": "Fired with the new value on every keystroke."
      }
    ],
    "relatedTypes": {}
  },
  "Textarea": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Description'",
        "description": "Field label."
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false,
        "default": "'Placeholder text'",
        "description": "Hint shown when empty. Not a substitute for the label."
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "Current value. Controlled — pair with onChange."
      },
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "default": "4",
        "description": "Visible text rows."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Vertical padding density."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Filled' | 'Error' | 'Disabled' | 'ReadOnly'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Hover`, `Focused` and `Filled` are presentation-only — leave them unset in application code, where CSS drives them from the real pointer and keyboard. `Error`, `Disabled` and `ReadOnly` are real application state and belong in your code."
      },
      {
        "name": "showLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Show the field label."
      },
      {
        "name": "helpText",
        "type": "string",
        "required": false,
        "description": "Guidance shown below the field. Replaced by errorText when invalid."
      },
      {
        "name": "errorText",
        "type": "string",
        "required": false,
        "description": "Validation message. Linked to the control via aria-describedby."
      },
      {
        "name": "maxLength",
        "type": "number",
        "required": false,
        "description": "Maximum character length."
      },
      {
        "name": "showCount",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Show character counter."
      },
      {
        "name": "onChange",
        "type": "(value: string) => void",
        "required": false,
        "description": "Fired with the new value on every keystroke."
      }
    ],
    "relatedTypes": {}
  },
  "Toggle": {
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": false,
        "default": "'Toggle setting'",
        "description": "Text beside the switch describing the setting."
      },
      {
        "name": "checked",
        "type": "boolean",
        "required": false,
        "description": "On / off state."
      },
      {
        "name": "state",
        "type": "'Default' | 'Hover' | 'Focused' | 'Disabled'",
        "required": false,
        "default": "'Default'",
        "description": "Freezes a visual state so documentation can show it without a pointer. `Hover` and `Focused` are presentation-only — leave them unset in application code, where CSS drives them from the real pointer and keyboard. `Disabled` is real application state and belongs in your code."
      },
      {
        "name": "size",
        "type": "'Small' | 'Medium'",
        "required": false,
        "default": "'Medium'",
        "description": "Track / thumb size."
      },
      {
        "name": "withLabel",
        "type": "boolean",
        "required": false,
        "default": "true",
        "description": "Render the label."
      },
      {
        "name": "onChange",
        "type": "(checked: boolean) => void",
        "required": false,
        "description": "Fired with the new on/off state."
      }
    ],
    "relatedTypes": {}
  },
  "Tooltip": {
    "props": [
      {
        "name": "content",
        "type": "string",
        "required": false,
        "default": "'Supplementary help text'",
        "description": "The hint text. Keep it short; never put essential information here alone."
      },
      {
        "name": "placement",
        "type": "'Top' | 'Bottom' | 'Left' | 'Right'",
        "required": false,
        "default": "'Top'",
        "description": "Position relative to the trigger."
      },
      {
        "name": "theme",
        "type": "'Light' | 'Dark'",
        "required": false,
        "default": "'Dark'",
        "description": "Surface color."
      },
      {
        "name": "type",
        "type": "'Default' | 'Accessibility'",
        "required": false,
        "default": "'Default'",
        "description": "Accessibility type uses larger text."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The element the tooltip describes."
      },
      {
        "name": "forceVisible",
        "type": "boolean",
        "required": false,
        "default": "false",
        "description": "Keep the tooltip visible regardless of hover — used for documentation."
      }
    ],
    "relatedTypes": {}
  }
}
