// GENERATED by scripts/build-portable.ts - which components use each radius
// token, read from the component source. Do not edit.

export const radiusUsage: Record<string, string[]> = {
  "none": [],
  "xs": [
    "Checkbox",
    "Link",
    "Rating"
  ],
  "sm": [
    "Button",
    "DatePicker",
    "Dialog",
    "List",
    "Menu",
    "Popover",
    "SegmentedControl",
    "Select",
    "Skeleton",
    "Tabs",
    "Tooltip"
  ],
  "md": [
    "Accordion",
    "Alert",
    "DatePicker",
    "Drawer",
    "FileUpload",
    "List",
    "Menu",
    "OtpInput",
    "Pagination",
    "Popover",
    "SegmentedControl",
    "Select",
    "Skeleton",
    "Snackbar",
    "Table",
    "Tabs",
    "TextInput",
    "Textarea"
  ],
  "lg": [
    "Card",
    "Dialog",
    "Stat"
  ],
  "xl": [],
  "pill": [
    "Avatar",
    "Badge",
    "Dialog",
    "Progress",
    "RadioButton",
    "Skeleton",
    "Slider",
    "Stepper",
    "Tag",
    "Toggle",
    "Tooltip"
  ]
}
